//------------------------------------------------------------------------------
// <auto-generated>
  //     此代码由工具生成。
  //     2013/3/6 14:21:42
  //     对此文件的更改可能会导致不正确的行为，并且如果
  //     重新生成代码，这些更改将会丢失。
  //     http://www.shangpin.com/
// </auto-generated>
//------------------------------------------------------------------------------
namespace Shangpin.Entity.WfsExport
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	

    [Table(Name="dbo.DataSyncLog")]
    [Database(Name ="ComBeziWfsExport" )]
    public partial class DataSyncLog
    {
        
        [Column(Storage="SequenceId", DbType="int(4)", CanBeNull=false, IsPrimaryKey=true,IsDbGenerated=true)]
        public Int32  SequenceId { get; set; }
        
        [Column(Storage="DatabaseName", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  DatabaseName { get; set; }
        
        [Column(Storage="TableName", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  TableName { get; set; }
        
        [Column(Storage="FieldName", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FieldName { get; set; }
        
        [Column(Storage="FieldValue", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FieldValue { get; set; }
        
        [Column(Storage="ActionType", DbType="varchar(50)", CanBeNull=true, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  ActionType { get; set; }
        
        [Column(Storage="DataXmlText", DbType="ntext(16)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  DataXmlText { get; set; }
        
        [Column(Storage="IsError", DbType="int(4)", CanBeNull=true, IsPrimaryKey=false,IsDbGenerated=false)]
        public Int32  IsError { get; set; }
        
        [Column(Storage="ErrorCount", DbType="int(4)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public Int32  ErrorCount { get; set; }
        
        [Column(Storage="DateCreate", DbType="datetime(8)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public DateTime  DateCreate { get; set; }
            }


    [Table(Name="dbo.OrderDataSyncLog")]
    [Database(Name ="ComBeziWfsExport" )]
    public partial class OrderDataSyncLog
    {
        
        [Column(Storage="SequenceId", DbType="int(4)", CanBeNull=false, IsPrimaryKey=true,IsDbGenerated=true)]
        public Int32  SequenceId { get; set; }
        
        [Column(Storage="DatabaseName", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  DatabaseName { get; set; }
        
        [Column(Storage="TableName", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  TableName { get; set; }
        
        [Column(Storage="FieldName", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FieldName { get; set; }
        
        [Column(Storage="FieldValue", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FieldValue { get; set; }
        
        [Column(Storage="ActionType", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  ActionType { get; set; }
        
        [Column(Storage="DataXmlText", DbType="ntext(16)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  DataXmlText { get; set; }
        
        [Column(Storage="IsError", DbType="int(4)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public Int32  IsError { get; set; }
        
        [Column(Storage="ErrorCount", DbType="int(4)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public Int32  ErrorCount { get; set; }
        
        [Column(Storage="DateCreate", DbType="datetime(8)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public DateTime  DateCreate { get; set; }
            }


    [Table(Name="dbo.UserDataSyncLog")]
    [Database(Name ="ComBeziWfsExport" )]
    public partial class UserDataSyncLog
    {
        
        [Column(Storage="SequenceId", DbType="int(4)", CanBeNull=false, IsPrimaryKey=true,IsDbGenerated=true)]
        public Int32  SequenceId { get; set; }
        
        [Column(Storage="DatabaseName", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  DatabaseName { get; set; }
        
        [Column(Storage="TableName", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  TableName { get; set; }
        
        [Column(Storage="FieldName", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FieldName { get; set; }
        
        [Column(Storage="FieldValue", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FieldValue { get; set; }
        
        [Column(Storage="ActionType", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  ActionType { get; set; }
        
        [Column(Storage="DataXmlText", DbType="ntext(16)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  DataXmlText { get; set; }
        
        [Column(Storage="IsError", DbType="int(4)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public Int32  IsError { get; set; }
        
        [Column(Storage="ErrorCount", DbType="int(4)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public Int32  ErrorCount { get; set; }
        
        [Column(Storage="DateCreate", DbType="datetime(8)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public DateTime  DateCreate { get; set; }
            }


}