//------------------------------------------------------------------------------
// <auto-generated>
  //     此代码由工具生成。
  //     2013-3-8 13:41:28
  //     对此文件的更改可能会导致不正确的行为，并且如果
  //     重新生成代码，这些更改将会丢失。
  //     http://www.shangpin.com/
// </auto-generated>
//------------------------------------------------------------------------------
namespace Shangpin.Entity.ComBeziPic
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	

    [Table(Name="dbo.ProductPictureFile")]
    [Database(Name ="ComBeziPic" )]
    public partial class ProductPictureFile
    {
        
        [Column(Storage="PictureFileNo", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=true,IsDbGenerated=false)]
        public String  PictureFileNo { get; set; }
        
        [Column(Storage="OperatorId", DbType="nvarchar(100)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  OperatorId { get; set; }
        
        [Column(Storage="FileName", DbType="nvarchar(400)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FileName { get; set; }
        
        [Column(Storage="Extension", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  Extension { get; set; }
        
        [Column(Storage="FileContent", DbType="nvarchar(-1)", CanBeNull=true, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FileContent { get; set; }
            }


    [Table(Name="dbo.ProductVideoFile")]
    [Database(Name ="ComBeziPic" )]
    public partial class ProductVideoFile
    {
        
        [Column(Storage="VideoFileNo", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=true,IsDbGenerated=false)]
        public String  VideoFileNo { get; set; }
        
        [Column(Storage="FileName", DbType="nvarchar(60)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FileName { get; set; }
        
        [Column(Storage="Extension", DbType="varchar(30)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  Extension { get; set; }
        
        [Column(Storage="FileContent", DbType="nvarchar(-1)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FileContent { get; set; }
        
        [Column(Storage="OperateUserId", DbType="varchar(30)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  OperateUserId { get; set; }
        
        [Column(Storage="DateOperate", DbType="datetime(8)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public DateTime  DateOperate { get; set; }
            }


    [Table(Name="dbo.SystemPictureFile")]
    [Database(Name ="ComBeziPic" )]
    public partial class SystemPictureFile
    {
        
        [Column(Storage="PictureFileNo", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=true,IsDbGenerated=false)]
        public String  PictureFileNo { get; set; }
        
        [Column(Storage="OperatorId", DbType="nvarchar(100)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  OperatorId { get; set; }
        
        [Column(Storage="FileName", DbType="nvarchar(400)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FileName { get; set; }
        
        [Column(Storage="Extension", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  Extension { get; set; }
        
        [Column(Storage="FileContent", DbType="nvarchar(-1)", CanBeNull=true, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FileContent { get; set; }
            }


    [Table(Name="dbo.UserPictureFile")]
    [Database(Name ="ComBeziPic" )]
    public partial class UserPictureFile
    {
        
        [Column(Storage="PictureFileNo", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=true,IsDbGenerated=false)]
        public String  PictureFileNo { get; set; }
        
        [Column(Storage="OperatorId", DbType="nvarchar(100)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  OperatorId { get; set; }
        
        [Column(Storage="FileName", DbType="nvarchar(400)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FileName { get; set; }
        
        [Column(Storage="Extension", DbType="varchar(50)", CanBeNull=false, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  Extension { get; set; }
        
        [Column(Storage="FileContent", DbType="nvarchar(-1)", CanBeNull=true, IsPrimaryKey=false,IsDbGenerated=false)]
        public String  FileContent { get; set; }
            }


}