//------------------------------------------------------------------------------
// <auto-generated>
  //     此代码由工具生成。
  //     2013/2/21 13:21:29
  //     对此文件的更改可能会导致不正确的行为，并且如果
  //     重新生成代码，这些更改将会丢失。
  //     http://www.shangpin.com/
// </auto-generated>
//------------------------------------------------------------------------------
namespace Shangpin.Entity.Common
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;


    [Table(Name = "dbo.Area")]
    [Database(Name = "ComBeziCommon")]
    public partial class Area
    {

        [Column(Storage = "AreaId", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = true, IsDbGenerated = true)]
        public Int32 AreaId { get; set; }

        [Column(Storage = "CityId", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int32 CityId { get; set; }

        [Column(Storage = "AreaName", DbType = "nvarchar(80)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String AreaName { get; set; }

        [Column(Storage = "PostCode", DbType = "varchar(6)", CanBeNull = true, IsPrimaryKey = false, IsDbGenerated = false)]
        public String PostCode { get; set; }
    }


    [Table(Name = "dbo.AutoSequence")]
    [Database(Name = "ComBeziCommon")]
    public partial class AutoSequence
    {

        [Column(Storage = "SequenceKey", DbType = "varchar(50)", CanBeNull = false, IsPrimaryKey = true, IsDbGenerated = false)]
        public String SequenceKey { get; set; }

        [Column(Storage = "SequenceId", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int32 SequenceId { get; set; }
    }


    [Table(Name = "dbo.City")]
    [Database(Name = "ComBeziCommon")]
    public partial class City
    {

        [Column(Storage = "CityId", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = true, IsDbGenerated = true)]
        public Int32 CityId { get; set; }

        [Column(Storage = "ProvinceId", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int32 ProvinceId { get; set; }

        [Column(Storage = "CityName", DbType = "nvarchar(80)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String CityName { get; set; }

        [Column(Storage = "PostCode", DbType = "varchar(6)", CanBeNull = true, IsPrimaryKey = false, IsDbGenerated = false)]
        public String PostCode { get; set; }
    }


    [Table(Name = "dbo.DictionaryGroup")]
    [Database(Name = "ComBeziCommon")]
    public partial class DictionaryGroup
    {

        [Column(Storage = "DictionaryGroupNo", DbType = "varchar(30)", CanBeNull = false, IsPrimaryKey = true, IsDbGenerated = false)]
        public String DictionaryGroupNo { get; set; }

        [Column(Storage = "DictionaryGroupName", DbType = "varchar(30)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String DictionaryGroupName { get; set; }

        [Column(Storage = "DictionaryGroupDesc", DbType = "varchar(50)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String DictionaryGroupDesc { get; set; }

        [Column(Storage = "SortValue", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int32 SortValue { get; set; }

        [Column(Storage = "DeleteFlag", DbType = "smallint(2)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int16 DeleteFlag { get; set; }
    }


    [Table(Name = "dbo.DictionaryItem")]
    [Database(Name = "ComBeziCommon")]
    public partial class DictionaryItem
    {

        [Column(Storage = "DictionaryItemNo", DbType = "varchar(30)", CanBeNull = false, IsPrimaryKey = true, IsDbGenerated = false)]
        public String DictionaryItemNo { get; set; }

        [Column(Storage = "DictionaryGroupNo", DbType = "varchar(30)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String DictionaryGroupNo { get; set; }

        [Column(Storage = "DictionaryItemName", DbType = "nvarchar(200)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String DictionaryItemName { get; set; }

        [Column(Storage = "DictionaryItemValue", DbType = "varchar(30)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String DictionaryItemValue { get; set; }

        [Column(Storage = "SortValue", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int32 SortValue { get; set; }

        [Column(Storage = "DeleteFlag", DbType = "smallint(2)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int16 DeleteFlag { get; set; }
    }


    [Table(Name = "dbo.Province")]
    [Database(Name = "ComBeziCommon")]
    public partial class Province
    {

        [Column(Storage = "ProvinceId", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = true, IsDbGenerated = true)]
        public Int32 ProvinceId { get; set; }

        [Column(Storage = "ProvinceName", DbType = "nvarchar(80)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String ProvinceName { get; set; }
    }


    [Table(Name = "dbo.SequenceCounter")]
    [Database(Name = "ComBeziCommon")]
    public partial class SequenceCounter
    {

        [Column(Storage = "SequenceKey", DbType = "varchar(50)", CanBeNull = false, IsPrimaryKey = true, IsDbGenerated = false)]
        public String SequenceKey { get; set; }

        [Column(Storage = "CounterId", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int32 CounterId { get; set; }
    }


    [Table(Name = "dbo.SystemLog")]
    [Database(Name = "ComBeziCommon")]
    public partial class SystemLog
    {

        [Column(Storage = "SystemLogID", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = true, IsDbGenerated = true)]
        public Int32 SystemLogID { get; set; }

        [Column(Storage = "Title", DbType = "nvarchar(200)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String Title { get; set; }

        [Column(Storage = "Content", DbType = "nvarchar(1200)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String Content { get; set; }

        [Column(Storage = "SysModelNo", DbType = "varchar(20)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String SysModelNo { get; set; }

        [Column(Storage = "SysModelName", DbType = "nvarchar(200)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String SysModelName { get; set; }

        [Column(Storage = "SysMenuNo", DbType = "varchar(20)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String SysMenuNo { get; set; }

        [Column(Storage = "SystemMenuName", DbType = "nvarchar(200)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String SystemMenuName { get; set; }

        [Column(Storage = "LogType", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int32 LogType { get; set; }

        [Column(Storage = "SysFlag", DbType = "smallint(2)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int16 SysFlag { get; set; }

        [Column(Storage = "UserID", DbType = "varchar(50)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String UserID { get; set; }

        [Column(Storage = "DateCreate", DbType = "datetime(8)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public DateTime DateCreate { get; set; }

        [Column(Storage = "OperatorNo", DbType = "varchar(30)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String OperatorNo { get; set; }

        [Column(Storage = "NoType", DbType = "smallint(2)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int16 NoType { get; set; }

        [Column(Storage = "OperatorType", DbType = "smallint(2)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int16 OperatorType { get; set; }

        [Column(Storage = "Status", DbType = "smallint(2)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int16 Status { get; set; }

        [Column(Storage = "StatusFlag", DbType = "varchar(10)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String StatusFlag { get; set; }
    }


    [Table(Name = "dbo.SystemLoginLog")]
    [Database(Name = "ComBeziCommon")]
    public partial class SystemLoginLog
    {

        [Column(Storage = "LoginLogID", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = true, IsDbGenerated = true)]
        public Int32 LoginLogID { get; set; }

        [Column(Storage = "UserID", DbType = "char(50)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String UserID { get; set; }

        [Column(Storage = "VerifyCode", DbType = "varchar(20)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String VerifyCode { get; set; }

        [Column(Storage = "LogStatus", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int32 LogStatus { get; set; }

        [Column(Storage = "SysFlag", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int32 SysFlag { get; set; }

        [Column(Storage = "LogTime", DbType = "datetime(8)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public DateTime LogTime { get; set; }

        [Column(Storage = "LogIP", DbType = "varchar(30)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String LogIP { get; set; }

        [Column(Storage = "ProvinceName", DbType = "nvarchar(40)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String ProvinceName { get; set; }

        [Column(Storage = "CityName", DbType = "nvarchar(40)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String CityName { get; set; }

        [Column(Storage = "Memo", DbType = "nvarchar(100)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String Memo { get; set; }
    }


    [Table(Name = "dbo.WebServiceOrder")]
    [Database(Name = "ComBeziCommon")]
    public partial class WebServiceOrder
    {

        [Column(Storage = "Id", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = true, IsDbGenerated = true)]
        public Int32 Id { get; set; }

        [Column(Storage = "FromDomain", DbType = "varchar(100)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String FromDomain { get; set; }

        [Column(Storage = "RequstType", DbType = "int(4)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int32 RequstType { get; set; }

        [Column(Storage = "XmlContent", DbType = "ntext(16)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public String XmlContent { get; set; }

        [Column(Storage = "TimeCreate", DbType = "datetime(8)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public DateTime TimeCreate { get; set; }

        [Column(Storage = "TimeAccept", DbType = "datetime(8)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public DateTime TimeAccept { get; set; }

        [Column(Storage = "Status", DbType = "smallint(2)", CanBeNull = false, IsPrimaryKey = false, IsDbGenerated = false)]
        public Int16 Status { get; set; }
    }



}