//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1008 版自动生成。
// 
#pragma warning disable 1591

namespace Shangpin.Ocs.Service.com.shangpin.erpws02 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ToWfsWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ToWfsWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateBrandMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductBuyPriceByProductNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SwapOrderCreateForWfsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SwapOrderDetailCancelForWfsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReturnApplyOrderCreateForWfsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCashTicketNoByAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInventoryAgeByProductNosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ToWfsWebService() {
            this.Url = global::Shangpin.Ocs.Service.Properties.Settings.Default.Shangpin_Ocs_Service_com_shangpin_erpws02_ToWfsWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdateBrandMessageCompletedEventHandler UpdateBrandMessageCompleted;
        
        /// <remarks/>
        public event GetProductBuyPriceByProductNoCompletedEventHandler GetProductBuyPriceByProductNoCompleted;
        
        /// <remarks/>
        public event SwapOrderCreateForWfsCompletedEventHandler SwapOrderCreateForWfsCompleted;
        
        /// <remarks/>
        public event SwapOrderDetailCancelForWfsCompletedEventHandler SwapOrderDetailCancelForWfsCompleted;
        
        /// <remarks/>
        public event ReturnApplyOrderCreateForWfsCompletedEventHandler ReturnApplyOrderCreateForWfsCompleted;
        
        /// <remarks/>
        public event GetCashTicketNoByAmountCompletedEventHandler GetCashTicketNoByAmountCompleted;
        
        /// <remarks/>
        public event GetInventoryAgeByProductNosCompletedEventHandler GetInventoryAgeByProductNosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateBrandMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateBrandMessage(string brandFiledXml) {
            object[] results = this.Invoke("UpdateBrandMessage", new object[] {
                        brandFiledXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateBrandMessageAsync(string brandFiledXml) {
            this.UpdateBrandMessageAsync(brandFiledXml, null);
        }
        
        /// <remarks/>
        public void UpdateBrandMessageAsync(string brandFiledXml, object userState) {
            if ((this.UpdateBrandMessageOperationCompleted == null)) {
                this.UpdateBrandMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateBrandMessageOperationCompleted);
            }
            this.InvokeAsync("UpdateBrandMessage", new object[] {
                        brandFiledXml}, this.UpdateBrandMessageOperationCompleted, userState);
        }
        
        private void OnUpdateBrandMessageOperationCompleted(object arg) {
            if ((this.UpdateBrandMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateBrandMessageCompleted(this, new UpdateBrandMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductBuyPriceByProductNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetProductBuyPriceByProductNo(string productNo) {
            object[] results = this.Invoke("GetProductBuyPriceByProductNo", new object[] {
                        productNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductBuyPriceByProductNoAsync(string productNo) {
            this.GetProductBuyPriceByProductNoAsync(productNo, null);
        }
        
        /// <remarks/>
        public void GetProductBuyPriceByProductNoAsync(string productNo, object userState) {
            if ((this.GetProductBuyPriceByProductNoOperationCompleted == null)) {
                this.GetProductBuyPriceByProductNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductBuyPriceByProductNoOperationCompleted);
            }
            this.InvokeAsync("GetProductBuyPriceByProductNo", new object[] {
                        productNo}, this.GetProductBuyPriceByProductNoOperationCompleted, userState);
        }
        
        private void OnGetProductBuyPriceByProductNoOperationCompleted(object arg) {
            if ((this.GetProductBuyPriceByProductNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductBuyPriceByProductNoCompleted(this, new GetProductBuyPriceByProductNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SwapOrderCreateForWfs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SwapOrderCreateForWfs(string paraxml) {
            object[] results = this.Invoke("SwapOrderCreateForWfs", new object[] {
                        paraxml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SwapOrderCreateForWfsAsync(string paraxml) {
            this.SwapOrderCreateForWfsAsync(paraxml, null);
        }
        
        /// <remarks/>
        public void SwapOrderCreateForWfsAsync(string paraxml, object userState) {
            if ((this.SwapOrderCreateForWfsOperationCompleted == null)) {
                this.SwapOrderCreateForWfsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSwapOrderCreateForWfsOperationCompleted);
            }
            this.InvokeAsync("SwapOrderCreateForWfs", new object[] {
                        paraxml}, this.SwapOrderCreateForWfsOperationCompleted, userState);
        }
        
        private void OnSwapOrderCreateForWfsOperationCompleted(object arg) {
            if ((this.SwapOrderCreateForWfsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SwapOrderCreateForWfsCompleted(this, new SwapOrderCreateForWfsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SwapOrderDetailCancelForWfs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SwapOrderDetailCancelForWfs(string ApplyOrderDetailId, string ApplyOrderNo) {
            object[] results = this.Invoke("SwapOrderDetailCancelForWfs", new object[] {
                        ApplyOrderDetailId,
                        ApplyOrderNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SwapOrderDetailCancelForWfsAsync(string ApplyOrderDetailId, string ApplyOrderNo) {
            this.SwapOrderDetailCancelForWfsAsync(ApplyOrderDetailId, ApplyOrderNo, null);
        }
        
        /// <remarks/>
        public void SwapOrderDetailCancelForWfsAsync(string ApplyOrderDetailId, string ApplyOrderNo, object userState) {
            if ((this.SwapOrderDetailCancelForWfsOperationCompleted == null)) {
                this.SwapOrderDetailCancelForWfsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSwapOrderDetailCancelForWfsOperationCompleted);
            }
            this.InvokeAsync("SwapOrderDetailCancelForWfs", new object[] {
                        ApplyOrderDetailId,
                        ApplyOrderNo}, this.SwapOrderDetailCancelForWfsOperationCompleted, userState);
        }
        
        private void OnSwapOrderDetailCancelForWfsOperationCompleted(object arg) {
            if ((this.SwapOrderDetailCancelForWfsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SwapOrderDetailCancelForWfsCompleted(this, new SwapOrderDetailCancelForWfsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReturnApplyOrderCreateForWfs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReturnApplyOrderCreateForWfs(string paraxml) {
            object[] results = this.Invoke("ReturnApplyOrderCreateForWfs", new object[] {
                        paraxml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnApplyOrderCreateForWfsAsync(string paraxml) {
            this.ReturnApplyOrderCreateForWfsAsync(paraxml, null);
        }
        
        /// <remarks/>
        public void ReturnApplyOrderCreateForWfsAsync(string paraxml, object userState) {
            if ((this.ReturnApplyOrderCreateForWfsOperationCompleted == null)) {
                this.ReturnApplyOrderCreateForWfsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnApplyOrderCreateForWfsOperationCompleted);
            }
            this.InvokeAsync("ReturnApplyOrderCreateForWfs", new object[] {
                        paraxml}, this.ReturnApplyOrderCreateForWfsOperationCompleted, userState);
        }
        
        private void OnReturnApplyOrderCreateForWfsOperationCompleted(object arg) {
            if ((this.ReturnApplyOrderCreateForWfsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnApplyOrderCreateForWfsCompleted(this, new ReturnApplyOrderCreateForWfsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCashTicketNoByAmount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCashTicketNoByAmount(string ticketAmount) {
            object[] results = this.Invoke("GetCashTicketNoByAmount", new object[] {
                        ticketAmount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCashTicketNoByAmountAsync(string ticketAmount) {
            this.GetCashTicketNoByAmountAsync(ticketAmount, null);
        }
        
        /// <remarks/>
        public void GetCashTicketNoByAmountAsync(string ticketAmount, object userState) {
            if ((this.GetCashTicketNoByAmountOperationCompleted == null)) {
                this.GetCashTicketNoByAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCashTicketNoByAmountOperationCompleted);
            }
            this.InvokeAsync("GetCashTicketNoByAmount", new object[] {
                        ticketAmount}, this.GetCashTicketNoByAmountOperationCompleted, userState);
        }
        
        private void OnGetCashTicketNoByAmountOperationCompleted(object arg) {
            if ((this.GetCashTicketNoByAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCashTicketNoByAmountCompleted(this, new GetCashTicketNoByAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInventoryAgeByProductNos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetInventoryAgeByProductNos(string ticketAmount) {
            object[] results = this.Invoke("GetInventoryAgeByProductNos", new object[] {
                        ticketAmount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetInventoryAgeByProductNosAsync(string ticketAmount) {
            this.GetInventoryAgeByProductNosAsync(ticketAmount, null);
        }
        
        /// <remarks/>
        public void GetInventoryAgeByProductNosAsync(string ticketAmount, object userState) {
            if ((this.GetInventoryAgeByProductNosOperationCompleted == null)) {
                this.GetInventoryAgeByProductNosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInventoryAgeByProductNosOperationCompleted);
            }
            this.InvokeAsync("GetInventoryAgeByProductNos", new object[] {
                        ticketAmount}, this.GetInventoryAgeByProductNosOperationCompleted, userState);
        }
        
        private void OnGetInventoryAgeByProductNosOperationCompleted(object arg) {
            if ((this.GetInventoryAgeByProductNosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInventoryAgeByProductNosCompleted(this, new GetInventoryAgeByProductNosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateBrandMessageCompletedEventHandler(object sender, UpdateBrandMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateBrandMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateBrandMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetProductBuyPriceByProductNoCompletedEventHandler(object sender, GetProductBuyPriceByProductNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductBuyPriceByProductNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductBuyPriceByProductNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SwapOrderCreateForWfsCompletedEventHandler(object sender, SwapOrderCreateForWfsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SwapOrderCreateForWfsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SwapOrderCreateForWfsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SwapOrderDetailCancelForWfsCompletedEventHandler(object sender, SwapOrderDetailCancelForWfsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SwapOrderDetailCancelForWfsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SwapOrderDetailCancelForWfsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReturnApplyOrderCreateForWfsCompletedEventHandler(object sender, ReturnApplyOrderCreateForWfsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnApplyOrderCreateForWfsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnApplyOrderCreateForWfsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCashTicketNoByAmountCompletedEventHandler(object sender, GetCashTicketNoByAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCashTicketNoByAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCashTicketNoByAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetInventoryAgeByProductNosCompletedEventHandler(object sender, GetInventoryAgeByProductNosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInventoryAgeByProductNosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInventoryAgeByProductNosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591